package com.redhat.poc.solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HOADetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean hoaMembership;
   private java.util.Date hoaMeetingDate;

   public HOADetails()
   {
   }

   public java.lang.Boolean getHoaMembership()
   {
      return this.hoaMembership;
   }

   public void setHoaMembership(java.lang.Boolean hoaMembership)
   {
      this.hoaMembership = hoaMembership;
   }

   public java.util.Date getHoaMeetingDate()
   {
      return this.hoaMeetingDate;
   }

   public void setHoaMeetingDate(java.util.Date hoaMeetingDate)
   {
      this.hoaMeetingDate = hoaMeetingDate;
   }

   public HOADetails(java.lang.Boolean hoaMembership,
         java.util.Date hoaMeetingDate)
   {
      this.hoaMembership = hoaMembership;
      this.hoaMeetingDate = hoaMeetingDate;
   }

}