package com.redhat.poc.solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class NewOrder implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "NEWORDER_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "NEWORDER_ID_SEQ", name = "NEWORDER_ID_GENERATOR")
   private java.lang.Long id;

   private java.lang.String orderID;

   private java.util.Date orderDate;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   private com.redhat.poc.solarvillage.PropertyAddress propertyAddress;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   private com.redhat.poc.solarvillage.HOADetails hoaDetails;

   public NewOrder()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getOrderID()
   {
      return this.orderID;
   }

   public void setOrderID(java.lang.String orderID)
   {
      this.orderID = orderID;
   }

   public java.util.Date getOrderDate()
   {
      return this.orderDate;
   }

   public void setOrderDate(java.util.Date orderDate)
   {
      this.orderDate = orderDate;
   }

   public com.redhat.poc.solarvillage.PropertyAddress getPropertyAddress()
   {
      return this.propertyAddress;
   }

   public void setPropertyAddress(
         com.redhat.poc.solarvillage.PropertyAddress propertyAddress)
   {
      this.propertyAddress = propertyAddress;
   }

   public com.redhat.poc.solarvillage.HOADetails getHoaDetails()
   {
      return this.hoaDetails;
   }

   public void setHoaDetails(com.redhat.poc.solarvillage.HOADetails hoaDetails)
   {
      this.hoaDetails = hoaDetails;
   }

   public NewOrder(java.lang.Long id, java.lang.String orderID,
         java.util.Date orderDate,
         com.redhat.poc.solarvillage.PropertyAddress propertyAddress,
         com.redhat.poc.solarvillage.HOADetails hoaDetails)
   {
      this.id = id;
      this.orderID = orderID;
      this.orderDate = orderDate;
      this.propertyAddress = propertyAddress;
      this.hoaDetails = hoaDetails;
   }

}