package com.redhat.poc.solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PropertyAddress implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String propertyAddressLine1;
   private java.lang.String propertyAddressLine2;
   private java.lang.String city;
   private java.lang.String state;
   private java.lang.Integer zipCode;
   private java.lang.String country;

   public PropertyAddress()
   {
   }

   public java.lang.String getPropertyAddressLine1()
   {
      return this.propertyAddressLine1;
   }

   public void setPropertyAddressLine1(java.lang.String propertyAddressLine1)
   {
      this.propertyAddressLine1 = propertyAddressLine1;
   }

   public java.lang.String getPropertyAddressLine2()
   {
      return this.propertyAddressLine2;
   }

   public void setPropertyAddressLine2(java.lang.String propertyAddressLine2)
   {
      this.propertyAddressLine2 = propertyAddressLine2;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public java.lang.Integer getZipCode()
   {
      return this.zipCode;
   }

   public void setZipCode(java.lang.Integer zipCode)
   {
      this.zipCode = zipCode;
   }

   public java.lang.String getCountry()
   {
      return this.country;
   }

   public void setCountry(java.lang.String country)
   {
      this.country = country;
   }

   public PropertyAddress(java.lang.String propertyAddressLine1,
         java.lang.String propertyAddressLine2, java.lang.String city,
         java.lang.String state, java.lang.Integer zipCode,
         java.lang.String country)
   {
      this.propertyAddressLine1 = propertyAddressLine1;
      this.propertyAddressLine2 = propertyAddressLine2;
      this.city = city;
      this.state = state;
      this.zipCode = zipCode;
      this.country = country;
   }

}